<?php

require_once('vendor/autoload.php');
require_once("requires/json2latex.php");

use JansenFelipe\SdapsPHP\SdapsPHP;



//Gets the SDAPS project name and parses out the ../
$projectPath = $_POST['instruments'];
$projectPath = str_replace('..'.DIRECTORY_SEPARATOR, '', $projectPath);

//Pulls records IDs of printouts to make from user-checked checkboxes
$records = array();
$recordIds = array();
if(isset($_POST['records']) && !empty($_POST['records'])) {
    //Unserializes the data in the records array sent by create_project.js
    parse_str($_POST['records'], $records);

    //parse_str returns 2-dim array, first dim is the class name of serialized data
    foreach($records as $record) {
        //Run through every ID checked
        foreach($record as $key => $value) {
            //Convert the string IDs to integers
            $recordIds[$key] = (int)$value;
        }
    }
}

//Only stamp printouts with record IDs if we have more than one
if(sizeof($recordIds) > 0) {
    //Stamp the records
    SdapsPHP::stampIDs($projectPath, $recordIds);

    //Create the message output echoed by the js file
    echo 'Created printouts for records: ';
    foreach($recordIds as $key => $id) {
        if($key === (sizeof($recordIds)-1)) {
            //Add semicolon since data after it will be parsed as iframe filepath
            echo ' '.$id.".;";
        }
        else {
            echo ' '.$id.',';
        }
    }

    //Echoes the path to the new printout generated by the user
    $stampedDocs = glob($projectPath.DIRECTORY_SEPARATOR.'stamped_*.pdf');
    echo '..'.DIRECTORY_SEPARATOR.$stampedDocs[sizeof($stampedDocs)-1];
}
//If we don't have any documents to generate
else {
    echo "No documents generated.  Select 1 or more records to create printouts for.\r\n";
}

?>